### ISSUE TITLE
I'm excited for this!

### ISSUE THREAD

**Issue by bendichter** [BlackrockMicrosystems/Python-Utilities#1]
Is there a timeline for when we can expect to see python tools distributed?

Thanks,
Ben

**Comment by NHalper** [comment]
Ben, 

There are some basic ones written. It looks like my team hasn't gotten them on to Github yet. I will reach out to them and get that handled in the next week or so. 

Nick

**Comment by bendichter** [comment]
@NHalper I found this: http://blackrockmicro.com/wp-content/uploads/2016/08/brPY.zip

Is this what you would recommend using?

**Comment by bendichter** [comment]
@NHalper any progress on getting those tools up?

**Comment by NHalper** [comment]
Ben, Stephen hasn't gotten them up on Github yet, but they are available on our website: http://blackrockmicro.com/technical-support/software-downloads/ under brPy
